const fs = require('fs');
const path = require('path');
const xmlbuilder = require('xmlbuilder');

// Generates enrolments.xml inside 'course'
// course\enrolments.xml
function generateEnrolmentXml(courseDir) {
    const enrolmentsXml = xmlbuilder.create('enrolments', { encoding: 'UTF-8' })
        .ele('enrols')
            .ele('enrol', { id: '13660' })
                .ele('enrol', 'manual').up()
                .ele('status', '0').up()
                .ele('name', '$@NULL@$').up()
                .ele('enrolperiod', '0').up()
                .ele('enrolstartdate', '0').up()
                .ele('enrolenddate', '0').up()
                .ele('expirynotify', '0').up()
                .ele('expirythreshold', '86400').up()
                .ele('notifyall', '0').up()
                .ele('password', '$@NULL@$').up()
                .ele('cost', '$@NULL@$').up()
                .ele('currency', '$@NULL@$').up()
                .ele('roleid', '5').up()
                .ele('customint1', '$@NULL@$').up()
                .ele('customint2', '$@NULL@$').up()
                .ele('customint3', '$@NULL@$').up()
                .ele('customint4', '$@NULL@$').up()
                .ele('customint5', '$@NULL@$').up()
                .ele('customint6', '$@NULL@$').up()
                .ele('customint7', '$@NULL@$').up()
                .ele('customint8', '$@NULL@$').up()
                .ele('customchar1', '$@NULL@$').up()
                .ele('customchar2', '$@NULL@$').up()
                .ele('customchar3', '$@NULL@$').up()
                .ele('customdec1', '$@NULL@$').up()
                .ele('customdec2', '$@NULL@$').up()
                .ele('customtext1', '$@NULL@$').up()
                .ele('customtext2', '$@NULL@$').up()
                .ele('customtext3', '$@NULL@$').up()
                .ele('customtext4', '$@NULL@$').up()
                .ele('timecreated', '1717536492').up()
                .ele('timemodified', '1717536492').up()
                .ele('user_enrolments').up()
            .up()
            .ele('enrol', { id: '13661' })
                .ele('enrol', 'guest').up()
                .ele('status', '1').up()
                .ele('name', '$@NULL@$').up()
                .ele('enrolperiod', '0').up()
                .ele('enrolstartdate', '0').up()
                .ele('enrolenddate', '0').up()
                .ele('expirynotify', '0').up()
                .ele('expirythreshold', '0').up()
                .ele('notifyall', '0').up()
                .ele('password', '').up()
                .ele('cost', '$@NULL@$').up()
                .ele('currency', '$@NULL@$').up()
                .ele('roleid', '0').up()
                .ele('customint1', '$@NULL@$').up()
                .ele('customint2', '$@NULL@$').up()
                .ele('customint3', '$@NULL@$').up()
                .ele('customint4', '$@NULL@$').up()
                .ele('customint5', '$@NULL@$').up()
                .ele('customint6', '$@NULL@$').up()
                .ele('customint7', '$@NULL@$').up()
                .ele('customint8', '$@NULL@$').up()
                .ele('customchar1', '$@NULL@$').up()
                .ele('customchar2', '$@NULL@$').up()
                .ele('customchar3', '$@NULL@$').up()
                .ele('customdec1', '$@NULL@$').up()
                .ele('customdec2', '$@NULL@$').up()
                .ele('customtext1', '$@NULL@$').up()
                .ele('customtext2', '$@NULL@$').up()
                .ele('customtext3', '$@NULL@$').up()
                .ele('customtext4', '$@NULL@$').up()
                .ele('timecreated', '1717536492').up()
                .ele('timemodified', '1717536492').up()
                .ele('user_enrolments').up()
            .up()
        .up()
        .end({ pretty: true });

    fs.writeFileSync(path.join(courseDir, 'enrolments.xml'), enrolmentsXml);

    return enrolmentsXml;
}

module.exports = generateEnrolmentXml;