const fs = require('fs');
const path = require('path');
const xmlbuilder = require('xmlbuilder');

// Generates moodle_backup.xml file inside 'final-mbz' directory
// final-mbz\moodle_backup.xml
function createMoodleBackup(finalDir) {
    const backupXml = xmlbuilder.create('moodle_backup', { encoding: 'UTF-8' })
        .ele('information')
            .ele('name', 'Rakentamisen muovit, moduuli 1: Miksi rakentamisen muoveja pitää kerätä ja kierrättää?.mbz').up()
            .ele('moodle_version', '2022112814.03').up()
            .ele('moodle_release', '4.1.14+ (Build: 20241101)').up()
            .ele('backup_version', '2022112800').up()
            .ele('backup_release', '4.1').up()
            .ele('backup_date', '1731674744').up()
            .ele('mnet_remoteusers', '0').up()
            .ele('include_files', '0').up()
            .ele('include_file_references_to_external_content', '0').up()
            .ele('original_wwwroot', 'https://moodle.metropolia.fi').up()
            .ele('original_site_identifier_hash', 'ddc026eaa3a68b0dc3bf0f757a1ba639').up()
            .ele('original_course_id', '5630').up()
            .ele('original_course_format', 'topics').up()
            .ele('original_course_fullname', 'Rakentamisen muovit, moduuli 1: Miksi rakentamisen muoveja pitää kerätä ja kierrättää?').up()
            .ele('original_course_shortname', 'rakentamisen-muovit-miksi-rakentamisen-muoveja-pitaa-kerata-ja-kierrattaa').up()
            .ele('original_course_startdate', '1733126400').up()
            .ele('original_course_enddate', '1764662400').up()
            .ele('original_course_contextid', '1050905').up()
            .ele('original_system_contextid', '1').up()
            .ele('details')
                .ele('detail', { backup_id: '46a34a7756b995108a6dd87c4b00e270' })
                    .ele('type', 'course').up()
                    .ele('format', 'moodle2').up()
                    .ele('interactive', '1').up()
                    .ele('mode', '10').up()
                    .ele('execution', '1').up()
                    .ele('executiontime', '0').up()
                .up()
            .up()
            .ele('contents')
                .ele('course')
                    .ele('courseid', '5630').up()
                    .ele('title', 'rakentamisen-muovit-miksi-rakentamisen-muoveja-pitaa-kerata-ja-kierrattaa').up()
                    .ele('directory', 'course').up()
                .up()
                .ele('activities')
                    .ele('activity')
                        .ele('moduleid', '5874').up()
                        .ele('sectionid', '5633').up()
                        .ele('modulename', 'book_5874').up()
                        .ele('title', 'Kurssin sisältö').up()
                        .ele('directory', 'activities/book_5874').up()
                        .up()
                    .ele('activity')
                        .ele('moduleid', '5898').up()
                        .ele('sectionid', '5633').up()
                        .ele('modulename', 'book_5898').up()
                        .ele('title', 'Kurssin sisältö').up()
                        .ele('modulename', 'activities/book_5898').up()
                    .up()
                    .ele('activity')
                        .ele('moduleid', '6117').up()
                        .ele('sectionid', '5633').up()
                        .ele('modulename', 'page_6117').up()
                        .ele('title', 'Kurssin sisältö').up()
                        .ele('directory', 'activities/page_6117').up()
                    .up()
                    .ele('activity')
                        .ele('moduleid', '6682').up()
                        .ele('sectionid', '5633').up()
                        .ele('modulename', 'page_6682').up()
                        .ele('title', 'Kurssin sisältö').up()
                        .ele('directory', 'activities/page_6682').up()
                    .up()
                .up()
                .ele('sections')
                    .ele('section')
                        .ele('sectionid', '5630').up()
                        .ele('title', 'General').up()
                        .ele('directory', 'sections/section_5630').up()
                    .up()
                    .ele('section')
                        .ele('sectionid', '5631').up()
                        .ele('title', 'Tervetuloa!').up()
                        .ele('directory', 'sections/section_5631').up()
                    .up()
                    .ele('section')
                        .ele('sectionid', '5632').up()
                        .ele('title', 'Ilmoittautuminen kurssille:').up()
                        .ele('directory', 'sections/section_5632').up()
                    .up()
                    .ele('section')
                        .ele('sectionid', '5633').up()
                        .ele('title', 'Rakentamisen muovit -koulutuskokonaisuus koostuu seuraavista moduuleista:​').up()
                        .ele('directory', 'sections/section_5633').up()
                    .up()
                .up()
            .up()
            .ele('settings')
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'filename').up()
                    .ele('value', 'rakentamisen-muovit-miksi-rakentamisen-muoveja-pitaa-kerata-ja-kierrattaa.mbz').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'imscc11').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'users').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'anonymize').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'role_assignments').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'activities').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'blocks').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'files').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'filters').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'comments').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'badges').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'calendarevents').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'userscompletion').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'logs').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'grade_histories').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'questionbank').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'groups').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'competencies').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'customfield').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'contentbankcontent').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'legacyfiles').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'section').up()
                    .ele('section', 'section_5630').up()
                    .ele('name', 'section_5630_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'section').up()
                    .ele('section', 'section_5631').up()
                    .ele('name', 'section_5631_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'section').up()
                    .ele('section', 'section_5632').up()
                    .ele('name', 'section_5632_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'section').up()
                    .ele('section', 'section_5633').up()
                    .ele('name', 'section_5633_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'book_5874').up()
                    .ele('name', 'book_5874_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'book_5874').up()
                    .ele('name', 'book_5874_userinfo').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'book_5898').up()
                    .ele('name', 'book_5898_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'book_5898').up()
                    .ele('name', 'book_5898_userinfo').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'page_6117').up()
                    .ele('name', 'page_6117_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'page_6117').up()
                    .ele('name', 'page_6117_userinfo').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'page_6682').up()
                    .ele('name', 'page_6682_included').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'activity').up()
                    .ele('activity', 'page_6682').up()
                    .ele('name', 'page_6682_userinfo').up()
                    .ele('value', '0').up()
                .up()
            .up()
        .up()
    .end({ pretty: true });

    fs.writeFileSync(path.join(finalDir, 'moodle_backup.xml'), backupXml);

    return backupXml;
}

module.exports = { createMoodleBackup };