const fs = require('fs');
const path = require('path');
const xmlbuilder = require('xmlbuilder');

// Generates moodle_backup.xml file inside 'output' directory
// output\moodle_backup.xml
function generateMoodleBackup(outputDir) {
    const backupXml = xmlbuilder.create('moodle_backup', { encoding: 'UTF-8' })
        .ele('information')
            .ele('name', 'backup-moodle2-course-4457-empty_course_10-20241115-1445-nu-nf.mbz').up()
            .ele('moodle_version', '2022112814.03').up()
            .ele('moodle_release', '4.1.14+ (Build: 20241101)').up()
            .ele('backup_version', '2022112800').up()
            .ele('backup_release', '4.1').up()
            .ele('backup_date', '1731674744').up()
            .ele('mnet_remoteusers', '0').up()
            .ele('include_files', '0').up()
            .ele('include_file_references_to_external_content', '0').up()
            .ele('original_wwwroot', 'https://moodle.metropolia.fi').up()
            .ele('original_site_identifier_hash', 'ddc026eaa3a68b0dc3bf0f757a1ba639').up()
            .ele('original_course_id', '4457').up()
            .ele('original_course_format', 'topics').up()
            .ele('original_course_fullname', 'Empty course 10').up()
            .ele('original_course_shortname', 'empty course 10').up()
            .ele('original_course_startdate', '1717621200').up()
            .ele('original_course_enddate', '1749157200').up()
            .ele('original_course_contextid', '1050905').up()
            .ele('original_system_contextid', '1').up()
            .ele('details')
                .ele('detail', { backup_id: '46a34a7756b995108a6dd87c4b00e270' })
                    .ele('type', 'course').up()
                    .ele('format', 'moodle2').up()
                    .ele('interactive', '1').up()
                    .ele('mode', '10').up()
                    .ele('execution', '1').up()
                    .ele('executiontime', '0').up()
                .up()
            .up()
            .ele('contents')
                .ele('course')
                    .ele('courseid', '4457').up()
                    .ele('title', 'empty course 10').up()
                    .ele('directory', 'course').up()
                .up()
            .up()
            .ele('settings')
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'filename').up()
                    .ele('value', 'backup-moodle2-course-4457-empty_course_10-20241115-1445-nu-nf.mbz').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'imscc11').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'users').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'anonymize').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'role_assignments').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'activities').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'blocks').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'files').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'filters').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'comments').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'badges').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'calendarevents').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'userscompletion').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'logs').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'grade_histories').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'questionbank').up()
                    .ele('value', '1').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'groups').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'competencies').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'customfield').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'contentbankcontent').up()
                    .ele('value', '0').up()
                .up()
                .ele('setting')
                    .ele('level', 'root').up()
                    .ele('name', 'legacyfiles').up()
                    .ele('value', '0').up()
                .up()
            .up()
        .up()
        .end({ pretty: true });

    fs.writeFileSync(path.join(outputDir, 'moodle_backup.xml'), backupXml);

    return backupXml;
}

module.exports = generateMoodleBackup;